export function adminPage(style: string) {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>PermitPilot · Workspace</title>${style}<style>textarea{font:inherit;width:100%;min-height:90px}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:10px;border-bottom:1px solid var(--rule)}.row{display:flex;gap:12px;flex-wrap:wrap}pre{white-space:pre-wrap;overflow-wrap:anywhere}main{max-width:1050px}.task{border-top:1px solid var(--rule);padding-top:16px}.task small{display:block}</style></head><body><main>
<header><p class="eyebrow">PermitPilot · Private operator workspace</p><h1>Permit history & follow-up tasks</h1><p class="muted">Track work your team chooses to do. Task status does not change the city’s permit status.</p></header>
<form id="login"><label>Workspace access key<input type="password" id="key" required autocomplete="off"></label><button>Unlock workspace</button><small>The key is kept only in this tab’s memory. Reload or lock the workspace to clear it.</small></form>
<p id="message" role="status"></p><section id="workspace" hidden><div class="row"><button id="refresh" type="button">Refresh captures</button><button id="lock" type="button">Lock workspace</button><a href="/">New live capture</a></div><div class="card" style="margin-top:20px;overflow:auto"><h2>Capture history</h2><table><thead><tr><th>Permit</th><th>Portal</th><th>Captured / requested</th><th>State</th><th>Actions</th></tr></thead><tbody id="jobs"></tbody></table></div>
<section id="detail" hidden class="card" style="margin-top:24px"><h2 id="selected"></h2><p>Use the source report to decide what needs follow-up. Tasks are coordinator notes, not an automated finding that a permit is deficient.</p><form id="create"><label>New task<input id="new-title" required maxlength="500" placeholder="Confirm the response addresses the structural review"></label><div class="row"><label>Owner<input id="new-owner" maxlength="120" placeholder="Name or team"></label><label>Due date<input id="new-due" type="date"></label></div><button>Add task</button></form><div id="tasks"></div></section></section>
</main><script>
let token='',jobId='';const el=id=>document.getElementById(id);const message=text=>{el('message').textContent=text;};
async function api(path,method='GET',body){const r=await fetch(path,{method,headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:body?JSON.stringify(body):undefined});const j=await r.json();if(!r.ok)throw new Error(j.error||'Request failed');return j;}
function node(tag,text){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;return n;}
function lock(){token='';jobId='';el('key').value='';el('jobs').replaceChildren();el('tasks').replaceChildren();el('workspace').hidden=true;el('detail').hidden=true;el('login').hidden=false;message('Workspace locked.');}
el('lock').onclick=lock;
async function jobs(){const list=await api('/api/admin/jobs');el('jobs').replaceChildren();for(const j of list){const tr=node('tr');for(const text of [j.permit,j.portal,new Date(j.createdAt).toLocaleString(),j.status])tr.append(node('td',text));const actions=node('td');const open=node('button','Tasks');open.type='button';open.onclick=()=>show(j.id,j.permit).catch(e=>message(e.message));actions.append(open);if(j.status==='completed'){const a=node('a',' Report');a.href='/r/'+j.id+'/report.html';a.target='_blank';a.rel='noopener';actions.append(a);}tr.append(actions);el('jobs').append(tr);}message(list.length+' recent captures loaded.');}
el('login').onsubmit=async e=>{e.preventDefault();token=el('key').value;el('key').value='';try{await jobs();el('login').hidden=true;el('workspace').hidden=false;}catch(x){token='';message(x.message);}};
el('refresh').onclick=()=>jobs().catch(e=>message(e.message));
async function show(id,permit){jobId=id;el('selected').textContent='Follow-up tasks · '+permit;el('detail').hidden=false;await tasks();}
function input(label,value,type='text'){const l=node('label',label),i=node('input');i.type=type;i.value=value||'';l.append(i);return [l,i];}
async function tasks(){const list=await api('/api/admin/jobs/'+jobId+'/tasks');el('tasks').replaceChildren();if(!list.length)el('tasks').append(node('p','No tasks yet. Add a follow-up above.'));for(const t of list){const form=node('form');form.className='task';const [tl,title]=input('Task',t.title);title.maxLength=500;title.required=true;const [ol,owner]=input('Owner',t.owner);owner.maxLength=120;const [dl,due]=input('Due date',t.dueDate,'date');const label=node('label','Task state'),state=node('select');for(const [v,n] of [['open','Open'],['in_progress','In progress'],['done','Done']]){const o=node('option',n);o.value=v;state.append(o);}state.value=t.status;label.append(state);const nl=node('label','Coordinator notes'),notes=node('textarea');notes.value=t.notes;notes.maxLength=4000;nl.append(notes);const save=node('button','Save changes');const audit=node('button','View edit history');audit.type='button';const history=node('pre');audit.onclick=async()=>{try{const entries=await api('/api/admin/tasks/'+t.id+'/audit');history.textContent=entries.map(a=>new Date(a.at).toLocaleString()+' · '+a.action+'\\n'+JSON.stringify(a.after_value,null,2)).join('\\n\\n');}catch(e){message(e.message);}};form.append(tl,ol,dl,label,nl,node('small','Revision '+t.version+' · '+new Date(t.updatedAt).toLocaleString()),save,audit,history);form.onsubmit=async e=>{e.preventDefault();save.disabled=true;try{await api('/api/admin/tasks/'+t.id,'PATCH',{title:title.value,owner:owner.value,dueDate:due.value||null,status:state.value,notes:notes.value,version:t.version});message('Task saved.');await tasks();}catch(x){message(x.message);save.disabled=false;}};el('tasks').append(form);}}
el('create').onsubmit=async e=>{e.preventDefault();const b=e.submitter;b.disabled=true;try{await api('/api/admin/jobs/'+jobId+'/tasks','POST',{title:el('new-title').value,owner:el('new-owner').value,dueDate:el('new-due').value||null,status:'open',notes:''});el('create').reset();await tasks();message('Task added.');}catch(x){message(x.message);}finally{b.disabled=false;}};
</script></body></html>`;
}
