import type { CaseAnalysisResult, CaseDocument } from './case-analysis.js';
export interface PublicCase { name:string; location:string; projectPage:string; caseIds:string[]; files:{id:string;url:string;pages:number;bytes:number;sha256:string;analyze:boolean}[] }
const esc=(s:unknown)=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function caseReport(c:PublicCase,a:CaseAnalysisResult,documents:CaseDocument[],run:{model:string;usage:unknown;at:string;reviewNotes?:string[]}) {
  const evidence=(es:CaseAnalysisResult['overview']['evidence'])=>`<details><summary>View source evidence</summary>${es.map(e=>{const file=c.files.find(f=>f.id===e.documentId)!;return `<blockquote>${esc(e.quote)}<footer><a href="${esc(file.url)}#page=${e.page}" target="_blank" rel="noopener">${esc(e.documentId)} · PDF page ${e.page}</a></footer></blockquote>`;}).join('')}</details>`;
  const unreadable=documents.flatMap(d=>d.pages.filter(p=>p.text.trim().length<80||p.textTruncated).map(p=>`${d.id}, page ${p.number}${p.textTruncated?' (truncated)':' (little/no text)'}`));
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Farmdale · PermitPilot</title><style>
:root{font:16px/1.6 system-ui;color:#20312e;background:#f4f5f0}body{max-width:1100px;margin:36px auto;padding:0 24px}h1{font-size:42px;line-height:1.1;margin:12px 0}h2{font-size:27px;margin-top:42px}h3{font-size:18px;margin:6px 0}a{color:#14685b}small,.muted{color:#52645e}.eyebrow{text-transform:uppercase;letter-spacing:.13em;font-size:12px}header{border-bottom:3px solid #197967;padding-bottom:24px}.notice{padding:16px;background:#fff1cc;border-radius:8px}.stats{display:flex;gap:18px;flex-wrap:wrap;margin:24px 0}.stat,article{background:#fff;border:1px solid #d7dfd8;border-radius:10px;padding:20px}.stat{flex:1;min-width:150px}.stat strong{display:block;font-size:28px}article{margin:12px 0}.tag{font-size:12px;background:#e7efeb;padding:4px 8px;border-radius:5px;text-transform:uppercase}table{width:100%;border-collapse:collapse;background:white}td,th{text-align:left;padding:12px;vertical-align:top;border-bottom:1px solid #d7dfd8}blockquote{border-left:3px solid #197967;padding:8px 16px;margin:12px 0;white-space:pre-wrap;font-size:14px}summary{cursor:pointer;color:#14685b;margin-top:12px}footer{font-size:12px}.two{display:grid;grid-template-columns:1fr 1fr;gap:18px}@media(max-width:700px){.two{grid-template-columns:1fr}h1{font-size:32px}table{font-size:13px}td,th{padding:8px}}nav{display:flex;gap:18px;flex-wrap:wrap;margin-top:18px}</style></head><body>
<header><span class="eyebrow">PermitPilot · Public case review · Live Solari + AIML</span><h1>${esc(c.name)}</h1><p>${esc(c.location)}<br><small>${esc(c.caseIds.join(' · '))}</small></p><p>${esc(a.overview.summary)}</p>${evidence(a.overview.evidence)}<nav><a href="#timeline">Timeline</a><a href="#changes">Decisions</a><a href="#tasks">Recorded tasks</a><a href="#questions">Review questions</a><a href="#documents">Documents</a></nav></header>
<div class="stats"><div class="stat"><strong>${c.files.reduce((n,f)=>n+f.pages,0)} pages</strong>Public packet indexed</div><div class="stat"><strong>${documents.reduce((n,d)=>n+d.pages.length,0)} pages</strong>Submitted for text analysis</div><div class="stat"><strong>${a.tasks.length} tasks</strong>Selected historical requirements</div></div>
<p class="notice"><b>${run.reviewNotes ? "Assistant-reviewed demonstration" : "AI draft — interpretation requires review"}.</b> Historical case research, not a permit approval or current compliance assessment. Task fulfillment is <b>unknown</b>. The ${c.files.filter(f=>!f.analyze).reduce((n,f)=>n+f.pages,0)} drawing pages are linked but have not been analyzed. Scanned content, signatures and engineering adequacy are not verified.</p>
<h2 id="timeline">1. Case timeline</h2><p>Application receipt, review and decisions are separate stages. Past deadlines are not current overdue alerts.</p>${[...a.timeline].sort((x,y)=>x.date.localeCompare(y.date)).map(t=>`<article><span class="tag">${esc(t.kind.replaceAll('_',' '))}</span> <time>${esc(t.date)}</time><h3>${esc(t.title)}</h3><p>${esc(t.detail)}</p>${evidence(t.evidence)}</article>`).join('')}
<h2 id="changes">2. Requested changes and recorded decisions</h2>${a.changes.map(t=>`<article><h3>${esc(t.topic)}</h3><div class="two"><div><b>Applicant requested</b><p>${esc(t.requested)}</p></div><div><b>Final decision records</b><p>${esc(t.decided)}</p></div></div>${evidence(t.evidence)}</article>`).join('')}
<h2 id="tasks">3. Recorded tasks to verify</h2><p>This selected list helps a coordinator find the supporting records. It does not establish that work is missing today or cover every condition.</p>${a.tasks.map(t=>`<article><span class="tag">Fulfillment unknown</span><h3>${esc(t.title)}</h3><p>${esc(t.action)}</p><p><b>Recorded timing:</b> ${esc(t.timing)}<br><small>Basis: ${esc(t.basis.replaceAll('_',' '))}</small></p>${evidence(t.evidence)}</article>`).join('')}
<h2 id="questions">4. Questions requiring confirmation</h2>${a.questions.map(t=>`<article><h3>${esc(t.title)}</h3><p>${esc(t.detail)}</p>${evidence(t.evidence)}</article>`).join('')}
<h2 id="documents">5. Document coverage</h2><table><thead><tr><th>Public document</th><th>Pages</th><th>Coverage</th></tr></thead><tbody>${c.files.map(f=>`<tr><td><a href="${esc(f.url)}" target="_blank" rel="noopener">${esc(f.id.replaceAll('-',' '))}</a><br><small>${(f.bytes/1e6).toFixed(1)} MB</small></td><td>${f.pages}</td><td>${f.analyze?'Text extracted in Solari; readable text sent to AIML':'Indexed only — drawing review pending'}</td></tr>`).join('')}</tbody></table>
<p>The packet includes repeated attachments. The original June final decision is not in this selected packet; obtain it before treating the conditions register as complete.</p><details><summary>Extraction limitations (${unreadable.length} pages)</summary><ul>${unreadable.map(p=>`<li>${esc(p)}</li>`).join('')}</ul></details>
${run.reviewNotes?`<h2>6. Review notes</h2><p>The assistant checked this example against the extracted records and made the following corrections. Original AI output is retained.</p><ul>${run.reviewNotes.map(n=>`<li>${esc(n)}</li>`).join('')}</ul><p><a href="reviewed-analysis.json">Reviewed example data</a></p>`:''}<h2>Run evidence</h2><p>Collected ${esc(run.at)} · Model: ${esc(run.model)}<br><a href="${esc(c.projectPage)}">Official project page</a> · <a href="analysis.json">AI analysis and usage</a> · <a href="documents.json">Extracted page text</a> · <a href="manifest.json">Run manifest</a> · <a href="project-page.png">Solari browser capture</a></p><p class="muted">Each evidence quote was checked against its extracted source page. This checks traceability, not the correctness of every AI interpretation. No application was generated or submitted for the owner.</p></body></html>`;
}
