import type { PortalAnalysisResult } from './portal-analysis.js';
import type { PortalCase } from './portal-etrakit.js';
import { disciplineChain, toIso, type Snapshot, type SnapshotDiff } from './portal-snapshot.js';
import type { PassageDocument, Evidence } from './passages.js';

const esc = (s: unknown) => String(s ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]!));
export interface PortalRun { model: string | null; usage: unknown; capturedAt: string; diff: SnapshotDiff | null; comparedWith: string | null; replay: Snapshot | null; analysis: PortalAnalysisResult | null; documents: PassageDocument[]; sessionId: string | null; checklistSkipped?: string | null; desktop?: { app: string; screenshot: string } | null; replaySaved?: boolean }

export function portalReport(c: PortalCase, s: Snapshot, run: PortalRun) {
  const docUrl = (documentId: string) => documentId.startsWith('review:') ? s.reviews.find(r => `review:${r.recordId}` === documentId)?.detailUrl : s.attachments.find(a => a.downloaded && `attachment:${a.downloaded.id}` === documentId)?.url;
  const evidence = (es: Evidence[]) => `<details><summary>View source evidence</summary>${es.map(e => `<blockquote>${esc(e.quote)}<footer><a href="${esc(docUrl(e.documentId) ?? '#')}" target="_blank" rel="noopener">${esc(e.documentId)} · page ${e.page}</a></footer></blockquote>`).join('')}</details>`;
  const cycles = [...new Set(s.reviews.map(r => toIso(r.submitted) ?? 'unknown'))].sort();
  const byCycle = (iso: string) => s.reviews.filter(r => (toIso(r.submitted) ?? 'unknown') === iso);
  const review = (id: string) => s.reviews.find(r => r.recordId === id);
  const d = run.diff;
  const diffHtml = !d ? '' : `<h2 id="changes">Change detection</h2><p>Compared with the snapshot captured ${esc(run.comparedWith)}. ${d.changed ? '<b>Portal content changed.</b>' : '<b>No change:</b> permit fields, review rows, reviewer notes and attachment labels are identical.'}</p>${d.changed ? `<ul>${d.permit.map(p => `<li>Permit ${esc(p.field)}: ${esc(p.from)} → ${esc(p.to)}</li>`).join('')}${d.reviews.added.map(id => `<li>New review row ${esc(id)}</li>`).join('')}${d.reviews.removed.map(id => `<li>Review row removed ${esc(id)}</li>`).join('')}${d.reviews.changed.map(x => `<li>Review ${esc(x.recordId)} changed: ${esc(x.fields.join(', '))}</li>`).join('')}${d.attachments.added.map(k => `<li>New attachment ${esc(k)}</li>`).join('')}${d.attachments.removed.map(k => `<li>Attachment removed ${esc(k)}</li>`).join('')}${d.attachments.changed.map(x => `<li>Attachment ${esc(x.key)} relabelled: ${esc(x.fields.join(', '))}</li>`).join('')}</ul>` : ''}`;
  const rp = run.replay;
  const replayHtml = !rp ? '' : `<h2 id="replay">Historical replay as of ${esc(rp.replay!.asOf)}</h2><p class="notice"><b>Reconstructed, not observed.</b> This view filters the event history captured ${esc(rp.replay!.from)} to what would have been visible on ${esc(rp.replay!.asOf)}. It is a coordinator's checkpoint for a finalized case, not a newly discovered update or a current obligation.</p><p>Status on that date: <b>${esc(rp.permit.status)}</b>. ${rp.reviews.length} review rows visible, ${rp.reviews.filter(r => r.status.startsWith('REPLAY')).length} still pending, ${rp.attachments.length} attachments uploaded.</p><table><thead><tr><th>Review</th><th>Reviewer</th><th>Status on ${esc(rp.replay!.asOf)}</th><th>Submitted</th></tr></thead><tbody>${rp.reviews.map(r => `<tr><td>${esc(r.type)}</td><td>${esc(r.reviewer)}</td><td>${esc(r.status)}</td><td>${esc(r.submitted)}</td></tr>`).join('')}</tbody></table>`;
  const a = run.analysis;
  const checklist = !a ? `<p class="muted">${esc(run.checklistSkipped ?? 'Model step skipped; the register above is the complete deterministic record.')}</p>` : `${a.items.map(i => { const r = review(i.reviewRecordId); return `<article><span class="tag">${esc(i.responseStatus.replaceAll('_', ' '))}</span><h3>${esc(r?.type)} · ${esc(r?.reviewer)} · submitted ${esc(r?.submitted)}</h3><p><b>Reviewer asked:</b> ${esc(i.commentSummary)}</p><p><b>Applicant response in packet:</b> ${esc(i.responseSummary)}${i.drawingReference ? ` <small>(points to ${esc(i.drawingReference)})</small>` : ''}</p><p><small>Portal outcome for this row: <b>${esc(r?.status)}</b>${r?.completed ? ` on ${esc(r.completed)}` : ''}. Later approvals are separate rows; nothing here verifies the drawing change itself.</small></p>${evidence(i.evidence)}</article>`; }).join('')}${a.questions.length ? `<h3>Questions for confirmation</h3>${a.questions.map(q => `<article><h3>${esc(q.title)}</h3><p>${esc(q.detail)}</p>${evidence(q.evidence)}</article>`).join('')}` : ''}`;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(c.permitNumber)} · PermitPilot</title><style>
:root{font:16px/1.6 system-ui;color:#20312e;background:#f4f5f0}body{max-width:1100px;margin:36px auto;padding:0 24px}h1{font-size:40px;line-height:1.1;margin:12px 0}h2{font-size:26px;margin-top:42px}h3{font-size:17px;margin:6px 0}a{color:#14685b}small,.muted{color:#52645e}.eyebrow{text-transform:uppercase;letter-spacing:.13em;font-size:12px}header{border-bottom:3px solid #197967;padding-bottom:24px}.notice{padding:16px;background:#fff1cc;border-radius:8px}.stats{display:flex;gap:18px;flex-wrap:wrap;margin:24px 0}.stat,article{background:#fff;border:1px solid #d7dfd8;border-radius:10px;padding:20px}.stat{flex:1;min-width:150px}.stat strong{display:block;font-size:26px}article{margin:12px 0}.tag{font-size:12px;background:#e7efeb;padding:4px 8px;border-radius:5px;text-transform:uppercase}table{width:100%;border-collapse:collapse;background:white}td,th{text-align:left;padding:10px;vertical-align:top;border-bottom:1px solid #d7dfd8}blockquote{border-left:3px solid #197967;padding:8px 16px;margin:12px 0;white-space:pre-wrap;font-size:14px}summary{cursor:pointer;color:#14685b;margin-top:12px}footer{font-size:12px}pre.notes{white-space:pre-wrap;font:14px/1.5 ui-monospace,monospace;background:#f7f8f4;padding:12px;border-radius:6px}.void{color:#8a2f2f;font-weight:600}nav{display:flex;gap:18px;flex-wrap:wrap;margin-top:18px}@media(max-width:700px){h1{font-size:30px}table{font-size:13px}td,th{padding:6px}}</style></head><body>
<header><span class="eyebrow">PermitPilot · Portal review monitor · Live Solari Browser + Sandbox${run.model ? ' + AIML' : ''}</span><h1>Permit ${esc(s.permitNumber)}</h1><p>${esc(c.authority)}<br>${esc(s.permit.siteAddress)} · ${esc(s.permit.type)} · ${esc(s.permit.description)}</p>${c.notes ? `<p><small>${esc(c.notes)}</small></p>` : ''}<nav><a href="#status">Status</a>${d ? '<a href="#changes">Changes</a>' : ''}${rp ? '<a href="#replay">Replay</a>' : ''}<a href="#cycles">Review cycles</a><a href="#register">Reviewer comments</a><a href="#checklist">Linked checklist</a><a href="#attachments">Attachments</a></nav></header>
<div class="stats"><div class="stat"><strong>${esc(s.permit.status)}</strong>Overall permit status</div><div class="stat"><strong>${s.reviews.length}</strong>Review rows</div><div class="stat"><strong>${cycles.length}</strong>Submission cycles</div><div class="stat"><strong>${s.attachments.length}</strong>Attachments listed (${s.attachments.filter(x => x.void).length} VOID)</div></div>
<p class="notice"><b>Public-record demonstration.</b> Captured ${esc(run.capturedAt)} from the portal with no login. The overall status is the permit's current state; individual review rows keep their historical DENIED or INCOMPLETE outcomes and must not be read as current problems. Applicant responses are assertions. No drawing content was verified and nothing was submitted or changed.</p>
<h2 id="status">Permit milestones</h2><table><tbody><tr><th>Applied</th><td>${esc(s.permit.appliedDate)}</td><th>Approved</th><td>${esc(s.permit.approvedDate)}</td></tr><tr><th>Issued</th><td>${esc(s.permit.issuedDate)}</td><th>Finaled</th><td>${esc(s.permit.finaledDate)}</td></tr><tr><th>Expiration</th><td>${esc(s.permit.expirationDate)}</td><th>Subtype</th><td>${esc(s.permit.subtype)}</td></tr></tbody></table>
${diffHtml}${replayHtml}
<h2 id="cycles">Review cycles</h2><p>Rows grouped by the portal's submitted date. Each cycle is one round of departmental review.</p>${cycles.map(cy => `<h3>Submitted ${esc(cy)}</h3><table><thead><tr><th>Review</th><th>Reviewer</th><th>Outcome</th><th>Completed</th><th>Due</th><th>Notes</th></tr></thead><tbody>${byCycle(cy).map(r => `<tr><td>${esc(r.type)}</td><td>${esc(r.reviewer)}</td><td>${esc(r.status)}</td><td>${esc(r.completed)}</td><td>${esc(r.dueDate)}</td><td>${r.notes.trim() ? `<a href="#r-${esc(r.recordId)}">yes</a>` : '<span class="muted">none</span>'}</td></tr>`).join('')}</tbody></table>`).join('')}
<h2 id="register">Reviewer comments, verbatim</h2><p>Copied from each review's public detail page. Text is the portal's own, including its capitalization.</p>${s.reviews.filter(r => r.notes.trim()).map(r => `<article id="r-${esc(r.recordId)}"><span class="tag">${esc(r.status)}</span><h3>${esc(r.type)} · ${esc(r.reviewer)} · submitted ${esc(r.submitted)}, completed ${esc(r.completed)}</h3>${r.remarks ? `<p><b>Remarks:</b> ${esc(r.remarks)}</p>` : ''}<pre class="notes">${esc(r.notes)}</pre><p><small><b>${esc(r.type.replace(/\s+EXPEDITE$/i, ''))} outcomes across cycles:</b> ${disciplineChain(s, r.recordId).map(x => `${esc(x.submitted)} → ${esc(x.status)}${x.completed ? ` (${esc(x.completed)})` : ''}`).join(' · ')}. Later rows are separate reviews; they do not say which change satisfied which comment.</small></p><small><a href="${esc(r.detailUrl)}" target="_blank" rel="noopener">Portal detail page</a> · SHA-256 ${esc(r.sha256.slice(0, 16))}…</small></article>`).join('')}
<h2 id="checklist">Comment-to-response checklist${a ? ' <small>(AI-linked, every quote checked against its source)</small>' : ''}</h2>${checklist}
${run.desktop ? `<h2 id="desktop">Tracker on a Solari Desktop</h2><p>The snapshot was written to <a href="tracker.csv">tracker.csv</a> on a Solari Desktop and opened in ${esc(run.desktop.app === 'libreoffice' ? 'LibreOffice Calc' : run.desktop.app)} on the real screen. The desktop was destroyed afterwards.</p><p><img src="${esc(run.desktop.screenshot)}" alt="Tracker spreadsheet open on a Solari Desktop" style="max-width:100%;border:1px solid #d7dfd8;border-radius:8px"></p>` : ''}
<h2 id="attachments">Attachments on the portal</h2><table><thead><tr><th>Portal label</th><th>File</th><th>Key timestamp hint</th><th>Downloaded</th></tr></thead><tbody>${s.attachments.length ? '' : '<tr><td colspan="4" class="muted">No attachments are published for this permit on the public portal.</td></tr>'}${s.attachments.map(x => `<tr><td>${x.void ? `<span class="void">${esc(x.label)}</span>` : esc(x.label)}</td><td><a href="${esc(x.url)}" target="_blank" rel="noopener">${esc(x.name)}</a></td><td>${esc(x.keyTimestampHint ?? '')}</td><td>${x.downloaded ? `${esc(x.downloaded.role.replaceAll('_', ' '))}, ${(x.downloaded.bytes / 1e3).toFixed(0)} kB, ${x.downloaded.matchesPinned ? 'hash matches pinned copy' : '<b>hash differs from pinned copy</b>'}` : ''}</td></tr>`).join('')}</tbody></table><p class="muted">The timestamp hint is read from the portal's attachment key and corroborated by the review submission dates; it is not a portal-labelled upload date.</p>
<h2>Run evidence</h2><p>Portal: <a href="${esc(s.portalUrl)}" target="_blank" rel="noopener">${esc(s.portalUrl)}</a>${run.model ? ` · Model: ${esc(run.model)}` : ''}<br><a href="snapshot.json">Snapshot</a> · <a href="documents.json">Extracted attachment text</a>${a ? ' · <a href="analysis.json">AI analysis and usage</a>' : ''}${d ? ' · <a href="diff.json">Diff</a>' : ''}${rp ? ' · <a href="replay.json">Replay</a>' : ''} · <a href="manifest.json">Manifest</a> · <a href="portal-search.png">Search</a> · <a href="portal-permit-info.png">Permit info</a> · <a href="portal-reviews.png">Reviews tab</a> · <a href="portal-review-detail.png">Review detail</a>${run.replaySaved ? ' · <a href="replay.ndjson">Session replay (rrweb)</a>' : ''} · <a href="tracker.csv">Tracker CSV</a></p><p class="muted">Solari Browser performed the search, tab navigation, detail-page reads and in-session attachment downloads. Solari Sandbox extracted attachment text in an isolated VM that was destroyed before any model call.</p></body></html>`;
}
