import type { Finding, Source } from './schema.js';
const esc = (s: unknown) => String(s).replace(/[&<>"']/g, ch => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[ch]!);
export function reportHTML(name: string, mode: string, findings: Finding[], sources: Source[]) {
  return `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>PermitPilot — ${esc(name)}</title>
<style>body{font:16px/1.6 system-ui;margin:40px auto;padding:0 24px;max-width:1050px;color:#182c32;background:#f7f8f4}header{border-bottom:3px solid #26726c;padding-bottom:18px}h1{font-size:32px}article{background:white;border:1px solid #cdd9d4;border-radius:8px;padding:18px;margin:16px 0}b.tag{font:12px system-ui;letter-spacing:.05em;text-transform:uppercase;border:1px solid;padding:5px 9px;border-radius:20px}h2{font-size:20px}blockquote{border-left:3px solid #26726c;padding-left:15px;margin-left:0}a{color:#12675f}.notice{background:#fff0cc;padding:16px}small{color:#43535a}</style>
<header><small>PERMITPILOT · DOCUMENT PREPARATION PROTOTYPE</small><h1>${esc(name)}</h1><p class="notice">${mode === 'live' ? 'LIVE: Solari Browser + Sandbox, AI page interpretation.' : 'LOCAL VERIFICATION: reference excerpts + deterministic fixture parser. No Solari or AI execution.'}<br>Draft only. Document evidence is not design approval or proof of a complete permit application.</p><a href="draft-application.pdf">Open unsigned draft application</a> · <a href="result.json">Structured findings</a></header>
${findings.map(f => `<article><b class="tag">${esc(f.status.replaceAll('_', ' '))}</b><h2>${esc(f.title)}</h2><p>${esc(f.explanation)}</p>${f.evidence.map(e => `<blockquote>${esc(e.quote)}<br><small><a href="inputs/${encodeURIComponent(e.documentId)}.pdf#page=${e.page}">${esc(e.documentId)}, page ${e.page}</a></small></blockquote>`).join('')}${f.sourceId ? `<small>Source: ${esc(f.sourceId)}</small>` : '<small>Project consistency check</small>'}</article>`).join('')}
<h2>Official references</h2>${sources.map(s => `<p><a href="${esc(s.url)}">${esc(s.title)}</a><br><small>${esc(s.mode)} · retrieved ${esc(s.capturedAt)} · SHA-256 ${esc(s.sha256)}</small></p>`).join('')}<p>Signatures, technical design review, parcel verification and conditional requirements remain with the applicant and responsible professionals.</p></html>`;
}
